AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Env:
    Type: String
    Description: The environment you're deploying to.
  SecurityGroupId:
    Type: 'AWS::EC2::SecurityGroup::Id'
    # Default: /inf/us-east-1/sg_shared
  SubnetId:
    Type: 'List<AWS::EC2::Subnet::Id>'
    # Default: /inf/us-east-1/sb_private
  # DomainName:
  #   Type: String
  #   Default: ${Env}-elasticsearch
  #   Description: Name of Elastic Search Domain
  EBSIOPS:
    # Type: Number
    # Default: 100
    Description: IOPS for attached EBS
    Type : 'String'
    # Default: '/elasticsearch/${Env}/EBSIOPS'
  EBSVolumeType:
    Type : 'String'
    # Default: '/elasticsearch/${Env}/EBS_VOLUME_TYPE'
    # Type: String
    # Default: gp2
    # AllowedValues:
    #   - gp2
    #   - io1
    #   - st1
    #   - sc1
  EBSVolumeSize:
    # Type: Number
    # Default: 10
    Description: EBS Volume Size
    Type : 'String'
    # Default: '/elasticsearch/${Env}/EBS_VOLUME_SIZE'
  InstanceCount:
    # Type: Number
    # Default: 1
    Description: Number of instances in Elastic Search Cluster
    Type : 'String'
    # Default: '/elasticsearch/${Env}/INSTANCE_COUNT'
  InstanceType:
    # Type: String
    # Default: r5.xlarge.elasticsearch
    Description: Type of instances in Elastic Search Cluster
    Type : 'String'
    # Default: '/elasticsearch/${Env}/INSTANCE_TYPE'    
    # AllowedValues:
    #   - c5.large.elasticsearch
    #   - c5.xlarge.elasticsearch
    #   - c5.2xlarge.elasticsearch
    #   - c5.4xlarge.elasticsearch
    #   - c5.9xlarge.elasticsearch
    #   - c5.18xlarge.elasticsearch
    #   - i3..large.elasticsearch
    #   - i3.xlarge.elasticsearch
    #   - i3.2xlarge.elasticsearch
    #   - i3.4xlarge.elasticsearch
    #   - i3.9xlarge.elasticsearch
    #   - i3.16xlarge.elasticsearch
    #   - m5.large.elasticsearch
    #   - m5.xlarge.elasticsearch
    #   - m5.2xlarge.elasticsearch
    #   - m5.4xlarge.elasticsearch
    #   - m5.12xlarge.elasticsearch
    #   - r5.large.elasticsearch
    #   - r5.xlarge.elasticsearch
    #   - r5.2xlarge.elasticsearch
    #   - r5.4xlarge.elasticsearch
    #   - r5.12xlarge.elasticsearch
    #   - t2.small.elasticsearch
    #   - t2.medium.elasticsearch
    #   - c4.large.elasticsearch
    #   - c4.xlarge.elasticsearch
    #   - c4.2xlarge.elasticsearch
    #   - c4.4xlarge.elasticsearch
    #   - c4.8xlarge.elasticsearch
    #   - i2.xlarge.elasticsearch
    #   - i2.2xlarge.elasticsearch
    #   - m4.large.elasticsearch
    #   - m4.xlarge.elasticsearch
    #   - m4.2xlarge.elasticsearch
    #   - m4.4xlarge.elasticsearch
    #   - m4.10xlarge.elasticsearch
    #   - r4.large.elasticsearch
    #   - r4.xlarge.elasticsearch
    #   - r4.2xlarge.elasticsearch
    #   - r4.4xlarge.elasticsearch
    #   - r4.8xlarge.elasticsearch
    #   - r4.16xlarge.elasticsearch
    #   - m3.medium.elasticsearch
    #   - m3.large.elasticsearch
    #   - m3.xlarge.elasticsearch
    #   - m3.2xlarge.elasticsearch
    #   - 4xlarge.elasticsearch
    #   - r3.large.elasticsearch
    #   - r3.xlarge.elasticsearch
    #   - r3.2xlarge.elasticsearch
    #   - r3.4xlarge.elasticsearch
    #   - r3.8xlarge.elasticsearch
      
  ElasticsearchVersion:
    Type: String
    Default: 7.4
    Description: Elastic Search Version
    AllowedValues:
      - 7.4
      - 7.1
      - 6.8
      - 6.7
      - 6.5
      - 6.4
      - 6.3
      - 6.2
      - 6.0
      - 5.6
      - 5.5
      - 5.3
      - 5.1
      - 2.3
      - 1.5
  # NameTagValue:
  #   Type: String
  #   Default: ${Env}-elasticsearch-cluster
  #   Description: Name Tag Value

  GroundstationMessageLogGroupName:
    # Type: Number
    # Default: /dxc/{$Env}/groundstation/messages
    Description: Groundstation Message Log Group Name for Streaming to ElasticSearch
    Type : 'String'

  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
    
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-confluent-kafka/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
    
Conditions: 
  IOPSCondition: !Equals [ !Ref EBSVolumeType, io1 ]


Resources:

  # ElasticSearchServiceLinkedRole:
  #   Type: AWS::IAM::ServiceLinkedRole
  #   Properties: 
  #     AWSServiceName: es.amazonaws.com
  #     #CustomSuffix: String
  #     Description: Service Linked Role for AWS Elastic Serch. Role for ES to access resources in VPC
  
  ElasticSearch:
    Type: AWS::Elasticsearch::Domain
    #DependsOn: ElasticSearchServiceLinkedRole
    Properties: 
      AccessPolicies:
        Version: '2012-10-17'
        Statement:

          - Effect: Allow
            Principal:
              #AWS: !GetAtt CognitoRole.Arn
              AWS: '*'
            Action: es:*
            Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${Env}-elasticsearch/*' #!Join ['',['arn:aws:es:',!Ref 'AWS::Region',':',!Ref 'AWS::AccountId',':domain/',!Sub '${Env}-elasticsearch',"/*"]]


          # - Effect: Allow
          #   Principal:
          #     AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${Env}-elasticsearch-lambda-role'
          #   Action: es:*
          #   Resource: !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${Env}-elasticsearch/*' #!Join ['',['arn:aws:es:',!Ref 'AWS::Region',':',!Ref 'AWS::AccountId',':domain/',!Sub '${Env}-elasticsearch',"/*"]]

      # AdvancedOptions: 
      #   Key : Value
      DomainName: !Sub '${Env}-elasticsearch'
      EBSOptions: 
        EBSEnabled: true
        Iops: !If [IOPSCondition, !Ref EBSIOPS, !Ref "AWS::NoValue"]
        VolumeSize: !Ref EBSVolumeSize
        VolumeType: !Ref EBSVolumeType
      ElasticsearchClusterConfig: 
        #DedicatedMasterCount: 0
        DedicatedMasterEnabled: false
        #DedicatedMasterType: r5.large.elasticsearch
        InstanceCount: !Ref InstanceCount  
        InstanceType: !Ref InstanceType
        ZoneAwarenessEnabled: false
      ElasticsearchVersion: !Ref ElasticsearchVersion
      # EncryptionAtRestOptions: 
      #   EncryptionAtRestOptions
      # NodeToNodeEncryptionOptions: 
      #   NodeToNodeEncryptionOptions
      # SnapshotOptions: 
      #   SnapshotOptions
      # Tags: 
      #   - Key: Name
      #     Value: !Ref NameTagValue
      VPCOptions: 
        SecurityGroupIds: 
          - !Ref SecurityGroupId
        SubnetIds:
          - !Select [ "1", !Ref SubnetId ]
          #- !Ref SubnetId

  GroundstationMessageLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Ref GroundstationMessageLogGroupName

  PermissionElasticsearchLoggingLambda:
    DependsOn: LambdaLogsToElasticsearch
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub LogsToElasticsearch_${Env}-elasticsearch
      Principal: logs.amazonaws.com
      #SourceArn: !Sub 'arn:aws:s3:::${S3AutosysNotificationsBucket}'

  GroundstationMessageSubFilter:
    DependsOn: 
      - GroundstationMessageLogGroup
      - PermissionElasticsearchLoggingLambda
      - LambdaLogsToElasticsearch
    Type: 'AWS::Logs::SubscriptionFilter'
    Properties:
      DestinationArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:LogsToElasticsearch_${Env}-elasticsearch
      LogGroupName: !Ref GroundstationMessageLogGroupName
      FilterPattern: "" #!Ref FilterPattern

  ElasticsearchEndpoint:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub /${Env}/ELASTICSEARCH_ENDPOINT
      Type: "String"
      Value: !GetAtt ElasticSearch.DomainEndpoint
  
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "LambdaElasticSearchExecutionRole"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: lambda-to-es-via-vpc-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'es:*' 
                Resource: '*'
        - PolicyName: logs-and-ec2-permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DeleteNetworkInterface'
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'

  LambdaLogsToElasticsearch:
    Type: 'AWS::Lambda::Function'
    DependsOn: 
      - LambdaExecutionRole
      - ElasticSearch
    Properties:
      FunctionName: !Sub LogsToElasticsearch_${Env}-elasticsearch
      Description: "CloudWatch Logs to Amazon ES streaming"
      Handler: "index.handler"
      Role:
        'Fn::GetAtt':
          - LambdaExecutionRole
          - Arn
      Runtime: "nodejs10.x"
      Timeout: 60
      VpcConfig:
        SecurityGroupIds: 
          - !Ref SecurityGroupId
        SubnetIds: 
          - !Select [ "1", !Ref SubnetId ]
      MemorySize: 128
      Environment:
        Variables: 
          ElasticDomainEndPoint: !GetAtt ElasticSearch.DomainEndpoint
      Code:
          S3Bucket: !Ref QSS3BucketName
          S3Key: !Sub ${QSS3KeyPrefix}lambda/index.js.zip